/**
 * 자동 뉴스 / 보도자료 기본 설정
 * route.ts에서 export하면 Next.js 빌드 에러가 발생하므로 별도 파일로 분리
 */
import type { AutoNewsSettings, AutoPressSettings } from "@/types/article";

export const DEFAULT_AUTO_NEWS_SETTINGS: AutoNewsSettings = {
  enabled: false,
  sources: [
    { id: "chosun",   name: "조선일보",  url: "https://www.chosun.com/arc/outboundfeeds/rss/?outputType=xml", enabled: true  },
    { id: "mk",       name: "매일경제",  url: "https://www.mk.co.kr/rss/30000001/",              enabled: true  },
    { id: "khan",     name: "경향신문",  url: "https://www.khan.co.kr/rss/rssdata/total_news.xml", enabled: false },
    { id: "yonhaptv", name: "연합뉴스TV", url: "https://www.yonhapnewstv.co.kr/browse/feed/",   enabled: false },
    { id: "gnews_ko", name: "Google 뉴스 (한국)", url: "https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko", enabled: false },
  ],
  keywords: [],
  category: "뉴스",
  count: 5,
  publishStatus: "임시저장",
  aiProvider: "gemini",
  aiModel: "gemini-2.0-flash",
  author: "",
  cronEnabled: false,
  dedupeWindowHours: 48,
};

export const DEFAULT_AUTO_PRESS_SETTINGS: AutoPressSettings = {
  enabled: false,
  sources: [
    { id: "gov_policy",   name: "정책뉴스 (netpro)",     boTable: "rss",      sca: "policy",       enabled: false, fetchType: "netpro" },
    { id: "gov_press",    name: "브리핑룸 (netpro)",     boTable: "rss",      sca: "pressrelease", enabled: false, fetchType: "netpro" },
    { id: "nw_all",       name: "뉴스와이어 전체",        boTable: "newswire", sca: "",             enabled: true,  fetchType: "netpro" },
    { id: "nw_economy",   name: "뉴스와이어 경제",        boTable: "newswire", sca: "100",          enabled: false, fetchType: "netpro" },
    { id: "nw_culture",   name: "뉴스와이어 문화",        boTable: "newswire", sca: "1200",         enabled: false, fetchType: "netpro" },
    { id: "kr_press",     name: "정부 보도자료",          boTable: "rss", sca: "", enabled: true,  fetchType: "rss", rssUrl: "https://www.korea.kr/rss/pressrelease.xml" },
    { id: "kr_policy",    name: "정부 정책뉴스",          boTable: "rss", sca: "", enabled: true,  fetchType: "rss", rssUrl: "https://www.korea.kr/rss/policy.xml" },
    { id: "kr_briefing",  name: "정부 부처 브리핑",       boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/ebriefing.xml" },
    { id: "kr_fact",      name: "사실은 이렇습니다",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/fact.xml" },
    { id: "kr_moef",      name: "기획재정부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_moef.xml" },
    { id: "kr_msit",      name: "과학기술정보통신부",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_msit.xml" },
    { id: "kr_mcst",      name: "문화체육관광부",         boTable: "rss", sca: "", enabled: true,  fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mcst.xml" },
    { id: "kr_motir",     name: "산업통상자원부",         boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_motir.xml" },
    { id: "kr_moel",      name: "고용노동부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_moel.xml" },
    { id: "kr_molit",     name: "국토교통부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_molit.xml" },
    { id: "kr_mw",        name: "보건복지부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mw.xml" },
    { id: "kr_moe",       name: "교육부",                boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_moe.xml" },
    { id: "kr_mcee",      name: "환경부",                boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mcee.xml" },
    { id: "kr_mois",      name: "행정안전부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mois.xml" },
    { id: "kr_fsc",       name: "금융위원회",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_fsc.xml" },
    { id: "kr_ftc",       name: "공정거래위원회",          boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_ftc.xml" },
    { id: "kr_mafra",     name: "농림축산식품부",          boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mafra.xml" },
    { id: "kr_mof",       name: "해양수산부",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mof.xml" },
    { id: "kr_mss",       name: "중소벤처기업부",          boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_mss.xml" },
    { id: "nwrss_all",    name: "뉴스와이어 전체 (직접)",  boTable: "rss", sca: "", enabled: true,  fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/all" },
    { id: "nwrss_it",     name: "뉴스와이어 IT",          boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/600" },
    { id: "nwrss_econ",   name: "뉴스와이어 경제",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/100" },
    { id: "nwrss_fin",    name: "뉴스와이어 금융",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/200" },
    { id: "nwrss_ind",    name: "뉴스와이어 산업",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/400" },
    { id: "nwrss_cult",   name: "뉴스와이어 문화",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1200" },
    { id: "nwrss_life",   name: "뉴스와이어 생활",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/900" },
    { id: "nwrss_health", name: "뉴스와이어 건강",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1000" },
    { id: "nwrss_edu",    name: "뉴스와이어 교육",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1100" },
    { id: "nwrss_env",    name: "뉴스와이어 환경",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1500" },
    { id: "nwrss_sport",  name: "뉴스와이어 스포츠",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1600" },
    { id: "nwrss_leisure",name: "뉴스와이어 레저",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1300" },
    { id: "nwrss_trans",  name: "뉴스와이어 물류/교통",   boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1800" },
    { id: "nwrss_social", name: "뉴스와이어 사회",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1900" },
    { id: "nwrss_agri",   name: "뉴스와이어 농수산",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1700" },
    { id: "nwrss_realty", name: "뉴스와이어 건설/부동산",  boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/300" },
    { id: "nwrss_auto",   name: "뉴스와이어 자동차",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/500" },
    { id: "nwrss_media",  name: "뉴스와이어 미디어",      boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/700" },
    { id: "nwrss_retail", name: "뉴스와이어 유통",        boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/800" },
    { id: "nwrss_gov",    name: "뉴스와이어 정부/정책",   boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/industry/1400" },
    { id: "nwrss_ir",     name: "뉴스와이어 상장기업 IR", boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/irnews" },
    { id: "nwrss_en",     name: "뉴스와이어 영문뉴스",    boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://api.newswire.co.kr/rss/english" },
    { id: "prn_all",      name: "PR Newswire 전체",       boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.prnewswire.com/kr/rss/news-releases-list.rss" },
    { id: "kr_npa",       name: "경찰청",                boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_npa.xml" },
    { id: "kr_nts",       name: "국세청",                boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_nts.xml" },
    { id: "kr_kma",       name: "기상청",                boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_kma.xml" },
    { id: "kr_kdca",      name: "질병관리청",             boTable: "rss", sca: "", enabled: false, fetchType: "rss", rssUrl: "https://www.korea.kr/rss/dept_kdca.xml" },
  ],
  keywords: [],
  category: "보도자료",
  count: 5,
  publishStatus: "임시저장",
  aiProvider: "gemini",
  aiModel: "gemini-2.0-flash",
  author: "",
  cronEnabled: false,
  dedupeWindowHours: 48,
  requireImage: true,
};
