// Generated by scripts/generate-live-preview-buckets.mjs. Do not edit manually.

import { renderPageBucketPreview } from "@/app/page-live-preview-render/PageBucketPreviewPage";
import { getPageComponentLoader } from "@/generated/page-live-preview/bucket-07";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ name: string }>;
}

export default function PageBucket07PreviewPage({ params }: PageProps) {
  return renderPageBucketPreview({
    params,
    bucket: "bucket-07",
    getPageComponentLoader,
  });
}
