// Generated by scripts/generate-live-preview-buckets.mjs. Do not edit manually.

import { renderRegistryBucketPreview } from "@/app/live-preview-render/RegistryBucketPreviewPage";
import { getRegistryComponentLoader } from "@/generated/live-preview-buckets/bucket-12";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ name: string }>;
}

export default function RegistryBucket12PreviewPage({ params }: PageProps) {
  return renderRegistryBucketPreview({
    params,
    bucket: "bucket-12",
    getRegistryComponentLoader,
  });
}
